apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/mysql"
