apiVersion: v1
kind: Service
metadata:
  name: backendservice
  namespace: default
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - name: backendservice
    protocol: TCP
    port: 8000
    targetPort: 8000

